/**
 * The brand, two parts:
 *
 *   BrandMark — the fire-service cross with a golf ball at its centre.
 *   Raster PNGs generated by scripts/build-brand.mjs (edit the drawing
 *   there), tinted to the theme's ink, so it inverts in dark mode.
 *
 *   BrandLogo — the wordmark. SITE_NAME, ink, letterspaced, the same
 *   word the emails wear.
 *
 * `size` on both is the rough width occupied, so call sites lay out
 * the same regardless of which part they mount.
 */

import React from 'react';
import { Text, Image, Platform } from 'react-native';
import { Colors } from '../../constants/colors';
import { FontFamily } from '../../constants/design';
import { SITE_NAME, SITE_LONG_NAME } from '../../constants/site';

interface LogoProps {
  /** Rough width in pixels. */
  size?: number;
  /** Ink. Defaults to Colors.textPrimary. */
  color?: string;
}

export function BrandMark({ size = 48, color }: LogoProps) {
  // Below ~28 px the line drawing's dimples and double strokes blur, so
  // small placements get the solid drawing. Both PNGs are one colour
  // with alpha; tintColor recolours them to the theme's ink.
  const source = size < 28
    ? require('../../assets/brand/nffga-mark-solid.png')
    : require('../../assets/brand/nffga-mark.png');
  return (
    <Image
      source={source}
      style={{ width: size, height: size, tintColor: color ?? Colors.textPrimary }}
      resizeMode="contain"
      accessibilityRole="image"
      accessibilityLabel={SITE_LONG_NAME}
    />
  );
}

export function BrandLogo({ size = 48, color }: LogoProps) {
  const fontSize = Math.max(12, Math.round(size * 0.42));
  return (
    <Text
      accessibilityRole="header"
      accessibilityLabel={SITE_NAME}
      style={{
        ...(Platform.OS === 'web' ? ({ fontFamily: FontFamily } as any) : {}),
        fontSize,
        lineHeight: Math.round(fontSize * 1.2),
        fontWeight: '800',
        letterSpacing: fontSize * 0.22,
        color: color ?? Colors.textPrimary,
      }}
    >
      {SITE_NAME}
    </Text>
  );
}
