/**
 * ShakespeareanInsults (web) — the themed module.
 *
 * Everything renders inside a single `.bard-root` wrapper. All theme
 * CSS is scoped to that class (variables live on `.bard-root`, never
 * `:root`), so the First-Folio look cannot leak into HereToo's global
 * styles. The IM Fell webfont is injected only when this component
 * mounts, i.e. only on this route.
 *
 * Content is entirely data-driven via lib/insultEngine (which reads
 * data/bard-insults.json). Nothing is hardcoded or generated by an LLM.
 */

import React, { useEffect, useMemo, useState } from 'react';
import {
  insultEngine, tierMeta,
  type Tier, type Meter, type Ending, type ForgeResult, type TrueLine,
} from '../lib/insultEngine';

const FONT_ID = 'bard-imfell-font';
const CSS_ID = 'bard-scoped-css';

function ensureAssets() {
  if (typeof document === 'undefined') return;
  if (!document.getElementById(FONT_ID)) {
    const link = document.createElement('link');
    link.id = FONT_ID;
    link.rel = 'stylesheet';
    link.href =
      'https://fonts.googleapis.com/css2?family=IM+Fell+English:ital@0;1&family=IM+Fell+English+SC&display=swap';
    document.head.appendChild(link);
  }
  if (!document.getElementById(CSS_ID)) {
    const style = document.createElement('style');
    style.id = CSS_ID;
    style.textContent = BARD_CSS;
    document.head.appendChild(style);
  }
}

export function ShakespeareanInsults() {
  useEffect(() => { ensureAssets(); }, []);

  const [tier, setTier] = useState<Tier>('safe');

  const [forgeRes, setForgeRes] = useState<ForgeResult | null>(null);
  const [spin, setSpin] = useState(0);
  const [meter, setMeter] = useState<Meter>('any');
  const [ending, setEnding] = useState<Ending>('masculine');
  const [strict, setStrict] = useState(false);

  const [line, setLine] = useState<TrueLine | null>(null);
  const [cascadeOn, setCascadeOn] = useState(false);
  const [cascade, setCascade] = useState<ForgeResult | null>(null);

  const epi = useMemo(() => insultEngine.epigraph(), []);

  const reduceMotion = typeof window !== 'undefined'
    && window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

  const strike = () => {
    const r = insultEngine.forge(tier, { meter, ending, strict });
    setForgeRes(r);
    setSpin((n) => n + 1);
  };
  const summon = () => setLine(insultEngine.summonLine(tier, { avoid: line?.text }));
  const runCascade = () => setCascade(insultEngine.diminutiveCascade(tier, 4));

  const anim = reduceMotion ? '' : 'bard-settle';

  return (
    <div className="bard-root">
      <div className="bard-frame">
        {/* Header */}
        <header className="bard-head">
          <h1 className="bard-title">Shakespearean Insults</h1>
          <p className="bard-epigraph">
            <span className="bard-dropcap">{epi.text.charAt(0)}</span>
            {epi.text.slice(1)}
          </p>
          <p className="bard-epi-attr">— {epi.speaker}, {epi.play}</p>
        </header>

        <div className="bard-fleuron" aria-hidden="true">❦</div>

        {/* Tier selector */}
        <div className="bard-tiers" role="group" aria-label="Sensitivity tier">
          {(['safe', 'edgy', 'full'] as Tier[]).map((t) => (
            <button
              key={t}
              className={`bard-tier ${tier === t ? 'is-on' : ''}`}
              onClick={() => setTier(t)}
              aria-pressed={tier === t}
            >
              {tierMeta(t).label}
            </button>
          ))}
        </div>
        <p className="bard-tier-desc">{tierMeta(tier).description}</p>

        {/* Forge */}
        <section className="bard-panel">
          <h2 className="bard-h2">The Forge</h2>
          <div className="bard-reels" aria-live="polite">
            {[0, 1, 2].map((i) => {
              const p = forgeRes?.parts[i];
              return (
                <div className="bard-reel" key={i}>
                  <div className={`bard-word ${anim}`} key={`${spin}-${i}`}>
                    {p ? p.term : '— — —'}
                  </div>
                  <div className="bard-word-src">{p ? p.play : ' '}</div>
                </div>
              );
            })}
          </div>

          <p className="bard-line" aria-live="polite">
            {forgeRes
              ? (forgeRes.scanned ? forgeRes.text : 'No line scanned that way — strike again.')
              : ' '}
          </p>

          <div className="bard-controls">
            <button className="bard-btn primary" onClick={strike}>Strike</button>
            <label className="bard-ctl">
              Meter
              <select
                className="bard-select"
                value={meter}
                onChange={(e) => setMeter((e.target as HTMLSelectElement).value as Meter)}
              >
                <option value="any">Off</option>
                <option value="iambicPentameter">Iambic pentameter</option>
                <option value="trochaicTetrameter">Trochaic tetrameter</option>
              </select>
            </label>
            {meter !== 'any' && (
              <label className="bard-ctl">
                Ending
                <select
                  className="bard-select"
                  value={ending}
                  onChange={(e) => setEnding((e.target as HTMLSelectElement).value as Ending)}
                >
                  <option value="masculine">Masculine</option>
                  <option value="feminine">Feminine</option>
                </select>
              </label>
            )}
            {meter === 'iambicPentameter' && (
              <label className="bard-ctl bard-switch">
                <input type="checkbox" checked={strict} onChange={(e) => setStrict((e.target as HTMLInputElement).checked)} />
                Strict
              </label>
            )}
          </div>
        </section>

        <div className="bard-fleuron" aria-hidden="true">❧</div>

        {/* Summon a True Line */}
        <section className="bard-panel">
          <h2 className="bard-h2">Summon a True Line</h2>
          <button className="bard-btn primary" onClick={summon}>Summon</button>
          {line && (
            <blockquote className="bard-clipping">
              <p className="bard-clip-text">“{line.text}”</p>
              <p className="bard-clip-attr">
                — {line.speaker}{line.target ? `, of ${line.target}` : ''}
              </p>
              <p className="bard-clip-cite">{line.play}{line.citation ? `, ${line.citation}` : ''}</p>
              {line.gloss && <p className="bard-clip-gloss">{line.gloss}</p>}
            </blockquote>
          )}
        </section>

        {/* Cascade (stretch) */}
        <section className="bard-panel">
          <label className="bard-switch">
            <input type="checkbox" checked={cascadeOn} onChange={(e) => setCascadeOn((e.target as HTMLInputElement).checked)} />
            Show the diminutive cascade
          </label>
          {cascadeOn && (
            <div className="bard-cascade">
              <button className="bard-btn" onClick={runCascade}>Cascade</button>
              {cascade && <p className="bard-line">{cascade.text}</p>}
            </div>
          )}
        </section>
      </div>
    </div>
  );
}

// ── Scoped theme ─────────────────────────────────────────────────────
// Every selector is prefixed with `.bard-root`. Variables live on the
// wrapper, not :root. Playhouse-warm, First-Folio print.

const BARD_CSS = `
.bard-root{
  --bard-ink:#1c1408; --bard-paper:#efe6cf; --bard-oak:#5b3a1e;
  --bard-plaster:#e7ddc4; --bard-madder:#9a2b1e; --bard-gilt:#b3893f;
  --bard-rule:rgba(179,137,63,.35);
  color:var(--bard-ink);
  font-family:"IM Fell English", Georgia, serif;
  max-width:760px; margin:0 auto; padding:24px 16px 80px;
  background:
    repeating-linear-gradient(0deg, transparent 0 3px, rgba(28,20,8,.018) 3px 4px),
    radial-gradient(120% 100% at 50% 0%, #f3ebd6, var(--bard-paper));
}
.bard-root *{box-sizing:border-box;}
.bard-root .bard-frame{
  border:1px solid var(--bard-oak); outline:1px solid var(--bard-rule);
  outline-offset:4px; padding:28px 22px; background:rgba(231,221,196,.35);
}
.bard-root .bard-head{text-align:center;}
.bard-root .bard-title{
  font-family:"IM Fell English SC","IM Fell English",serif;
  font-size:2.4rem; line-height:1.05; letter-spacing:.01em; margin:0 0 12px;
  color:var(--bard-ink);
}
.bard-root .bard-epigraph{
  font-style:italic; font-size:1.05rem; line-height:1.5; margin:0 auto; max-width:52ch;
}
.bard-root .bard-dropcap{
  float:left; font-size:2.6em; line-height:.8; padding:2px 8px 0 0;
  color:var(--bard-madder); font-family:"IM Fell English SC",serif;
}
.bard-root .bard-epi-attr{font-size:.85rem; color:var(--bard-oak); margin:6px 0 0; font-style:italic;}
.bard-root .bard-fleuron{text-align:center; color:var(--bard-gilt); font-size:1.4rem; margin:18px 0; letter-spacing:.4em;}

.bard-root .bard-tiers{display:flex; gap:8px; justify-content:center;}
.bard-root .bard-tier-desc{text-align:center; font-style:italic; font-size:.9rem; color:var(--bard-oak); margin:8px 0 0; min-height:2.4em;}

.bard-root button, .bard-root .bard-select, .bard-root .bard-input{
  font-family:"IM Fell English",Georgia,serif; color:var(--bard-ink);
}
.bard-root .bard-tier, .bard-root .bard-btn{
  cursor:pointer; background:var(--bard-plaster); border:1px solid var(--bard-oak);
  padding:8px 16px; font-size:1rem; transition:background .15s, color .15s;
}
.bard-root .bard-tier.is-on{background:var(--bard-madder); color:var(--bard-paper); border-color:var(--bard-madder);}
.bard-root .bard-btn.primary{background:var(--bard-oak); color:var(--bard-paper);}
.bard-root .bard-btn.ghost{background:transparent;}
.bard-root .bard-tier:focus-visible, .bard-root .bard-btn:focus-visible,
.bard-root .bard-select:focus-visible, .bard-root .bard-input:focus-visible,
.bard-root input:focus-visible{outline:2px solid var(--bard-gilt); outline-offset:2px;}

.bard-root .bard-gate{border:1px dashed var(--bard-oak); padding:14px; margin-top:14px; font-size:.95rem;}
.bard-root .bard-gate-row{display:flex; gap:8px; flex-wrap:wrap; align-items:center; margin:8px 0;}
.bard-root .bard-input{background:var(--bard-paper); border:1px solid var(--bard-oak); padding:7px 10px;}
.bard-root .bard-fine{font-size:.78rem; color:var(--bard-oak); font-style:italic; margin:4px 0 0;}

.bard-root .bard-panel{border-top:1px solid var(--bard-rule); margin-top:22px; padding-top:16px;}
.bard-root .bard-h2{font-family:"IM Fell English SC",serif; font-size:1.3rem; margin:0 0 12px; color:var(--bard-oak);}

.bard-root .bard-reels{display:flex; gap:12px; justify-content:center; flex-wrap:wrap; margin-bottom:10px;}
.bard-root .bard-reel{
  min-width:150px; flex:1; text-align:center; background:var(--bard-paper);
  border:1px solid var(--bard-oak); box-shadow:inset 0 0 0 2px var(--bard-plaster);
  padding:14px 10px; overflow:hidden;
}
.bard-root .bard-word{font-size:1.5rem; line-height:1.2; color:var(--bard-ink);}
.bard-root .bard-word-src{
  font-family:"IM Fell English SC",serif; font-size:.72rem; letter-spacing:.08em;
  text-transform:uppercase; color:var(--bard-oak); margin-top:6px;
}
@keyframes bard-settle{
  0%{transform:translateY(-18px); filter:blur(2px); opacity:.2;}
  70%{transform:translateY(2px); filter:blur(0); opacity:1;}
  100%{transform:translateY(0);}
}
.bard-root .bard-word.bard-settle{animation:bard-settle .42s cubic-bezier(.2,.8,.2,1);}

.bard-root .bard-line{
  text-align:center; font-size:1.5rem; line-height:1.4; min-height:1.4em;
  color:var(--bard-ink); margin:6px 0 16px;
}
.bard-root .bard-controls{display:flex; gap:12px; align-items:center; flex-wrap:wrap; justify-content:center;}
.bard-root .bard-ctl{display:flex; gap:6px; align-items:center; font-size:.9rem; color:var(--bard-oak);}
.bard-root .bard-select{background:var(--bard-paper); border:1px solid var(--bard-oak); padding:6px 8px;}
.bard-root .bard-switch{display:inline-flex; gap:6px; align-items:center; cursor:pointer; font-size:.9rem;}

.bard-root .bard-clipping{
  margin:14px 0 0; padding:16px 18px; background:var(--bard-paper);
  border:1px solid var(--bard-oak); box-shadow:2px 3px 0 rgba(28,20,8,.12);
}
.bard-root .bard-clip-text{font-size:1.25rem; line-height:1.45; margin:0 0 8px;}
.bard-root .bard-clip-attr{font-style:italic; margin:0; color:var(--bard-ink);}
.bard-root .bard-clip-cite{font-family:"IM Fell English SC",serif; font-size:.85rem; letter-spacing:.06em; color:var(--bard-oak); margin:2px 0 0;}
.bard-root .bard-clip-gloss{font-style:italic; font-size:.9rem; color:var(--bard-oak); margin:8px 0 0; border-top:1px solid var(--bard-rule); padding-top:8px;}
.bard-root .bard-cascade{margin-top:10px;}
@media (prefers-reduced-motion: reduce){
  .bard-root .bard-word.bard-settle{animation:none;}
}
`;
