-- ════════════════════════════════════════════════════════════════════════
-- HereToo — Migration 013: Founding-seed invites ("plant a tree")
-- ════════════════════════════════════════════════════════════════════════
-- Cameron has a friend in Texas with no connection to anyone on
-- HereToo. The existing /join/<CODE> flow brings that friend INTO an
-- existing family. We also want a flow that lets Cameron sponsor the
-- friend to start their OWN family (their tree), with Cameron and
-- the friend bound by an explicit connection so the network graph
-- reaches across the two trees.
--
-- Three pieces:
--
-- 1. `seed_invites` table — one-time tokens generated by a sponsor.
--    The token encodes "this person sponsored you to start a family
--    here." Single-use, expires after 30 days.
--
-- 2. RPCs: create_seed_invite, find_seed_invite (anon-readable
--    preview), accept_seed_invite (creates the new family for the
--    recipient + a connections row to the sponsor).
--
-- 3. `family_network_reach` updated to walk `connections` as well as
--    `family_members`, so a sponsor → seed connection lets the two
--    trees see each other's `connections`-visibility posts and counts
--    in the reach metric.
-- ════════════════════════════════════════════════════════════════════════

-- ── 1. seed_invites table ───────────────────────────────────────────────

create table if not exists public.seed_invites (
  id                    uuid primary key default gen_random_uuid(),
  token                 text not null unique
                          default encode(gen_random_bytes(12), 'hex'),
  sponsor_id            uuid not null references public.profiles(id) on delete cascade,
  message               text,
  suggested_family_name text,
  used_by               uuid references public.profiles(id) on delete set null,
  used_at               timestamptz,
  created_at            timestamptz not null default now(),
  expires_at            timestamptz not null default (now() + interval '30 days')
);

create index if not exists seed_invites_sponsor_idx on public.seed_invites(sponsor_id);

alter table public.seed_invites enable row level security;

-- Sponsor can read + manage their own.
drop policy if exists seed_self_rw on public.seed_invites;
create policy seed_self_rw on public.seed_invites
  for all to authenticated
  using (sponsor_id = auth.uid())
  with check (sponsor_id = auth.uid());

-- ── 2. RPC: create a seed invite ────────────────────────────────────────

create or replace function public.create_seed_invite(
  message_in               text default null,
  suggested_family_name_in text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  caller uuid := auth.uid();
  tok    text;
begin
  if caller is null then
    raise exception 'Must be signed in to create a seed invite';
  end if;
  insert into public.seed_invites (sponsor_id, message, suggested_family_name)
    values (caller, nullif(trim(coalesce(message_in,'')),''), nullif(trim(coalesce(suggested_family_name_in,'')),''))
    returning token into tok;
  return tok;
end$$;

grant execute on function public.create_seed_invite(text, text) to authenticated;

-- ── 3. Anon-readable preview by token ──────────────────────────────────

create or replace function public.find_seed_invite(token_in text)
returns table (
  token                 text,
  sponsor_id            uuid,
  sponsor_handle        text,
  sponsor_display_name  text,
  sponsor_avatar_path   text,
  message               text,
  suggested_family_name text,
  used                  boolean,
  expired               boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    si.token,
    si.sponsor_id,
    p.handle,
    p.display_name,
    p.avatar_path,
    si.message,
    si.suggested_family_name,
    si.used_by is not null as used,
    si.expires_at < now() as expired
  from public.seed_invites si
  left join public.profiles p on p.id = si.sponsor_id
  where si.token = token_in
  limit 1;
$$;

grant execute on function public.find_seed_invite(text) to anon, authenticated;

-- ── 4. Accept the seed invite: create the family + connection ──────────

create or replace function public.accept_seed_invite(
  token_in       text,
  family_name_in text
)
returns table (family_id uuid, connection_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  caller   uuid := auth.uid();
  invite   public.seed_invites%rowtype;
  fam_id   uuid;
  conn_id  uuid;
begin
  if caller is null then
    raise exception 'Must be signed in to accept a seed invite';
  end if;

  select * into invite from public.seed_invites where token = token_in;
  if not found then
    raise exception 'Seed invite not found';
  end if;
  if invite.used_by is not null then
    raise exception 'This seed has already been planted';
  end if;
  if invite.expires_at < now() then
    raise exception 'This seed invite has expired';
  end if;
  if invite.sponsor_id = caller then
    raise exception 'You cannot accept your own seed invite';
  end if;
  if length(trim(coalesce(family_name_in, ''))) < 2 then
    raise exception 'Pick a family name with at least 2 characters';
  end if;

  -- 4a. Create the recipient's new family. The families_add_owner_member
  -- trigger from migration 001 will auto-add the caller as the active
  -- 'owner' member, so we don't insert into family_members here.
  insert into public.families (owner_id, name, description)
    values (caller, trim(family_name_in), invite.message)
    returning id into fam_id;

  -- 4b. Connect the sponsor and recipient with status='accepted'.
  -- Sort the IDs so (requester, recipient) is stable for any pair.
  if invite.sponsor_id < caller then
    insert into public.connections (requester_id, recipient_id, status, accepted_at)
      values (invite.sponsor_id, caller, 'accepted', now())
      on conflict do nothing
      returning id into conn_id;
  else
    insert into public.connections (requester_id, recipient_id, status, accepted_at)
      values (caller, invite.sponsor_id, 'accepted', now())
      on conflict do nothing
      returning id into conn_id;
  end if;

  -- 4c. Mark the seed invite used.
  update public.seed_invites
     set used_by = caller, used_at = now()
   where id = invite.id;

  return query select fam_id, conn_id;
end$$;

grant execute on function public.accept_seed_invite(text, text) to authenticated;

-- ── 5. Connections in the network reach ────────────────────────────────
-- The original family_network_reach walks family_members only. Update
-- it so an accepted `connections` edge counts as a 1-hop link too.
-- Same depth bound, same block-list filter.

create or replace function public.family_network_reach(
  viewer    uuid,
  max_depth int default 3
)
returns table (profile_id uuid, hops int)
language sql stable security invoker
set search_path = public
as $$
  with recursive mesh as (
    -- Seed: the viewer at hop 0
    select viewer as profile_id, 0 as hops

    union

    -- Family-mate edge
    select fm_other.profile_id, m.hops + 1
    from mesh m
    join public.family_members fm_self
      on fm_self.profile_id = m.profile_id
     and fm_self.status = 'active'
    join public.family_members fm_other
      on fm_other.family_id = fm_self.family_id
     and fm_other.status = 'active'
     and fm_other.profile_id <> m.profile_id
    where m.hops < max_depth

    union

    -- Connection edge (accepted only)
    select case
             when c.requester_id = m.profile_id then c.recipient_id
             else c.requester_id
           end as profile_id,
           m.hops + 1
    from mesh m
    join public.connections c
      on c.status = 'accepted'
     and (c.requester_id = m.profile_id or c.recipient_id = m.profile_id)
    where m.hops < max_depth
  )
  select
    mesh.profile_id,
    min(mesh.hops) as hops
  from mesh
  where not public.are_blocked(viewer, mesh.profile_id)
  group by mesh.profile_id;
$$;

-- DONE.
